spring:
  application:
    name: tablemaster

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis

server:
  port: 8080

auth:
  validation:
    email:
      max-length: 30
    password:
      min-length: 8
      max-length: 30
      require-uppercase: true
      require-lowercase: true
      require-number: true
      require-special-char: true
    name:
      min-length: 2
      max-length: 30
    phone:
      pattern: "^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$"
